# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Example' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Example
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'ART',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTNetwork',
    'RCTText',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTWebSocket', # needed for debugging
    # Add any other subspecs you want to use in your project
  ]
  pod 'react-native-multiple-image-picker', :path => '../../'
  pod 'BLPhotoAssetPickerController', :path => '~/projects/BLPhotoAssetPickerController/'

  target 'ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
